global:
  scrape_interval: 15s
  # Configuraci√≥n para Alertmanager
  external_labels:
    monitor: 'docker-monitor'  # Etiqueta para identificar este prometheus

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Nombre del servicio de Alertmanager en Docker Compose

rule_files:
  - 'rules.yml'  # Importa las reglas de alerta

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]
      
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://nginx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115


